spring:
  application:
    name: backend

# 服务器配置
server:
  port: 10001
  servlet:
    context-path: /

# 日志配置
logging:
  level:
    com.dualtracklife.lifeagent: INFO
    org.springframework.web: INFO

